colors_basis <- gg_color_hue(n=3)
colors_base <- c("Original" = "black",
                 "MMUPHin corrected" = colors_basis[1])
colors_simulation_adjust.batch <- c("Original" = "black",
                                    "ComBat corrected" = colors_basis[3],
                                    "MMUPHin corrected" = colors_basis[1])
colors_simulation_lm.meta <- c("Original, naive analyzed" = "black",
                               "MMUPHin corrected, naive analyzed" = "brown",
                               "MMUPHin corrected, MMUPHin analyzed" = colors_basis[1])
colors_simulation_continuous <- c("Original, MMUPHin analyzed" = "brown",
                                  "MMUPHin corrected, MMUPHin analyzed" = colors_basis[1])
