l_tests <- list(
  # disease
  IBD_vs_control = list(test_variable = "IBD",
                        contrasts = list(IBD = "1",
                                         control = "0"),
                        batch_variable = "study_site",
                        covariates = c("gender_fill", "race_fill", "age.cat_fill"),
                        covariates.random = "subject_accession_longitudinal",
                        moderator_variables = c("sample_type"),
                        exprs_filter = quo(disease %in% c("CD", "UC", "control"))),
  CD_vs_control = list(test_variable = "disease",
                       contrasts = list(CD = "1",
                                        control = "0"),
                       batch_variable = "study_site",
                       covariates = c("gender_fill", "race_fill", "age.cat_fill"),
                       covariates.random = "subject_accession_longitudinal",
                       moderator_variables = c("sample_type"),
                       exprs_filter = quo(disease %in% c("CD", "control"))),
  UC_vs_control = list(test_variable = "disease",
                       contrasts = list(UC = "1",
                                        control = "0"),
                       batch_variable = "study_site",
                       covariates = c("gender_fill", "race_fill", "age.cat_fill"),
                       covariates.random = "subject_accession_longitudinal",
                       moderator_variables = c("sample_type"),
                       exprs_filter = quo(disease %in% c("UC", "control"))),
  CD_vs_UC = list(test_variable = "disease",
                  contrasts = list(CD = "1",
                                   UC = "0"),
                  batch_variable = "study_site",
                  covariates = c("gender_fill", "race_fill", "age.cat_fill"),
                  covariates.random = "subject_accession_longitudinal",
                  moderator_variables = c("sample_type"),
                  exprs_filter = quo(disease %in% c("CD", "UC"))),
  # treatment
  antibiotics = list(test_variable = "antibiotics",
                     contrasts = list("y" = "1",
                                      "n" = "0"),
                     batch_variable = "study_site_disease",
                     covariates = c("gender_fill", "race_fill", "age.cat_fill"),
                     covariates.random = "subject_accession_longitudinal",
                     moderator_variables = c("sample_type", "disease"),
                     exprs_filter = quo(disease %in% c("CD", "UC"))),
  immunosuppressants = list(test_variable = "immunosuppressants",
                            contrasts = list("y" = "1",
                                             "n" = "0"),
                            batch_variable = "study_site_disease",
                            covariates = c("gender_fill", "race_fill", "age.cat_fill"),
                            covariates.random = NULL,
                            moderator_variables = c("sample_type", "disease"),
                            exprs_filter = quo(disease %in% c("CD", "UC"))),
  steroids = list(test_variable = "steroids",
                  contrasts = list("y" = "1",
                                   "n" = "0"),
                  batch_variable = "study_site_disease",
                  covariates = c("gender_fill", "race_fill", "age.cat_fill"),
                  covariates.random = "subject_accession_longitudinal",
                  moderator_variables = c("sample_type", "disease"),
                  exprs_filter = quo(disease %in% c("CD", "UC"))),
  mesalamine_5ASA = list(test_variable = "mesalamine_5ASA",
                         contrasts = list("y" = "1",
                                          "n" = "0"),
                         batch_variable = "study_site_disease",
                         covariates = c("gender_fill", "race_fill", "age.cat_fill"),
                         covariates.random = "subject_accession_longitudinal",
                         moderator_variables = c("sample_type", "disease"),
                         exprs_filter = quo(disease %in% c("CD", "UC"))),
  # disease subtype
  L2_vs_L1 = list(test_variable = "L.cat",
                  contrasts = list("L1" = "0",
                                   "L1+L4" = "0",
                                   "L2" = "1",
                                   "L2+L4" = "1"),
                  batch_variable = "study_site",
                  covariates = c("gender_fill", "race_fill", "age.cat_fill"),
                  covariates.random = "subject_accession_longitudinal",
                  moderator_variables = c("sample_type"),
                  exprs_filter = quo(disease %in% c("CD") &
                                       L.cat %in% c("L1", "L1+L4", 
                                                    "L2", "L2+L4"))),
  L3_vs_L1 = list(test_variable = "L.cat",
                  contrasts = list("L1" = "0",
                                   "L1+L4" = "0",
                                   "L3" = "1",
                                   "L3+L4" = "1"),
                  batch_variable = "study_site",
                  covariates = c("gender_fill", "race_fill", "age.cat_fill"),
                  covariates.random = "subject_accession_longitudinal",
                  moderator_variables = c("sample_type"),
                  exprs_filter = quo(disease %in% c("CD") &
                                       L.cat %in% c("L1", "L1+L4", 
                                                    "L3", "L3+L4"))),
  L4 = list(test_variable = "L.cat",
            contrasts = list("L1" = "0",
                             "L2" = "0",
                             "L3" = "0",
                             "L1+L4" = "1",
                             "L2+L4" = "1",
                             "L3+L4" = "1"),
            batch_variable = "study_site",
            covariates = c("gender_fill", "race_fill", "age.cat_fill"),
            covariates.random = "subject_accession_longitudinal",
            moderator_variables = c("sample_type"),
            exprs_filter = quo(disease %in% c("CD"))),
  B2_vs_B1 = list(test_variable = "B.cat",
                  contrasts = list("B1" = "0",
                                   "B2" = "1"),
                  batch_variable = "study_site",
                  covariates = c("gender_fill", "race_fill", "age.cat_fill"),
                  covariates.random = "subject_accession_longitudinal",
                  moderator_variables = c("sample_type"),
                  exprs_filter = quo(disease %in% c("CD") &
                                       B.cat %in% c("B1", "B2"))),
  B3_vs_B1 = list(test_variable = "B.cat",
                  contrasts = list("B1" = "0",
                                   "B3" = "1"),
                  batch_variable = "study_site",
                  covariates = c("gender_fill", "race_fill", "age.cat_fill"),
                  covariates.random = "subject_accession_longitudinal",
                  moderator_variables = c("sample_type"),
                  exprs_filter = quo(disease %in% c("CD") &
                                       B.cat %in% c("B1", "B3"))),
  E2_vs_E1 = list(test_variable = "E.cat",
                  contrasts = list("E1" = "0",
                                   "E2" = "1"),
                  batch_variable = "study_site",
                  covariates = c("gender_fill", "race_fill", "age.cat_fill"),
                  covariates.random = "subject_accession_longitudinal",
                  moderator_variables = c("sample_type"),
                  exprs_filter = quo(disease %in% c("UC") &
                                       E.cat %in% c("E1", "E2"))),
  E3_vs_E1 = list(test_variable = "E.cat",
                  contrasts = list("E1" = "0",
                                   "E3" = "1"),
                  batch_variable = "study_site",
                  covariates = c("gender_fill", "race_fill", "age.cat_fill"),
                  covariates.random = "subject_accession_longitudinal",
                  moderator_variables = c("sample_type"),
                  exprs_filter = quo(disease %in% c("UC") &
                                       E.cat %in% c("E1", "E3"))),
  A2_vs_A1 = list(test_variable = "age_at_diagnosis.cat_fill",
                  contrasts = list("A1" = "0",
                                   "A2" = "1"),
                  batch_variable = "study_site_disease",
                  covariates = c("gender_fill", "race_fill", "age.cat_fill"),
                  covariates.random = "subject_accession_longitudinal",
                  moderator_variables = c("sample_type", "disease"),
                  exprs_filter = quo(disease %in% c("CD", "UC") &
                                       age_at_diagnosis.cat_fill %in% c("A1", "A2"))),
  A3_vs_A1 = list(test_variable = "age_at_diagnosis.cat_fill",
                  contrasts = list("A1" = "0",
                                   "A3" = "1"),
                  batch_variable = "study_site_disease",
                  covariates = c("gender_fill", "race_fill", "age.cat_fill"),
                  covariates.random = "subject_accession_longitudinal",
                  moderator_variables = c("sample_type", "disease"),
                  exprs_filter = quo(disease %in% c("CD", "UC") &
                                       age_at_diagnosis.cat_fill %in% c("A1", "A3"))),
  # covariates
  age = list(test_variable = "age.cat_fill",
             contrasts = list("child" = "0",
                              "adult" = "1"),
             batch_variable = "study_site_disease",
             covariates = c("race_fill", "gender_fill"),
             covariates.random = "subject_accession_longitudinal",
             moderator_variables = c("sample_type", "disease"),
             exprs_filter = quo(disease %in% c("CD", "UC", "control") &
                                  age.cat_fill %in% c("child", "adult"))),
  gender = list(test_variable = "gender_fill",
                contrasts = list("f" = "0",
                                 "m" = "1"),
                batch_variable = "study_site_disease",
                covariates = c("race_fill", "age.cat_fill"),
                covariates.random = "subject_accession_longitudinal",
                moderator_variables = c("sample_type", "disease"),
                exprs_filter = quo(disease %in% c("CD", "UC", "control") &
                                     gender_fill %in% c("f", "m")))
)
