---
title: "Time performance of MMUPHin and BDMMA on a subset of scenarios"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  df_print: paged
---
```{r setup, echo = FALSE}                                           
knitr::opts_knit$set(root.dir = normalizePath("../../"))
```
```{r setup2, message=FALSE, warning=FALSE, echo = FALSE}
smar::sourceDir("functions/", recursive = FALSE)
smar::sourceDir("functions/simulations/", recursive = FALSE)
setup("./")
dir_output <- "results/simulations/lm.meta/"
dir.create(dir_output, recursive = TRUE, showWarnings = TRUE)
dir.create(paste0(dir_output, "BDMMA/"), recursive = TRUE, showWarnings = TRUE)
```

```{r load data}
ncores <- 20
load(paste0(dir_output, "tb_sim.RData"))
```
```{r evaluate runtime}
tb_sim_subset <- tb_sim[1:20, ]
options(digits.secs = 12)

# time MMUPHin
doParallel::registerDoParallel(ncores)
times_MMUPHin <- foreach::`%dopar%`(
  foreach::foreach(i = tb_sim_subset$i),
  {
    mat_otu <- read.table(paste0(dir_output,
                                 "sparseDOSSA_sets/",
                                 i, ".tsv"),
                          header = TRUE,
                          sep = "\t",
                          row.names = 1) %>%
      as.matrix
    i_simSetup <- tb_sim[i, ]
    df_metadata <- i_simSetup$df_metadata[[1]]
    
    start_time <- Sys.time()
    mat_otu <- mat_otu %>%
      MMUPHin::adjust.batch(batch = "batch",
                            covariates = "exposure",
                            data = df_metadata,
                            diagnostics = FALSE,
                            verbose = FALSE)
    
    fit_lm.meta <- MMUPHin::lm.meta(
      feature.abd = mat_otu,
      batch = "batch",
      exposure = "exposure",
      data = df_metadata,
      normalization = "TSS",
      transform = "AST",
      output = paste0(dir_output, "MMUPHin_after/", i, "/"),
      forest.plots = FALSE,
      verbose = FALSE)
    
    return(Sys.time() - start_time)
  }
) 
doParallel::stopImplicitCluster()
save(times_MMUPHin, file = paste0(dir_output, "time_MMUPHin.RData"))

# time BDMMA
doParallel::registerDoParallel(ncores)
times_BDMMA <- foreach::`%dopar%`(
  foreach::foreach(i = tb_sim_subset$i),
  {
    mat_otu <- read.table(paste0(dir_output,
                                 "sparseDOSSA_sets/",
                                 i, ".tsv"),
                          header = TRUE,
                          sep = "\t",
                          row.names = 1) %>%
      as.matrix
    i_simSetup <- tb_sim[i, ]
    df_metadata <- i_simSetup$df_metadata[[1]] %>% 
      dplyr::transmute(main = as.numeric(as.character(exposure)),
                       confounder = NA_real_,
                       batch = as.numeric(as.character(batch)))
    sSet <- SummarizedExperiment::SummarizedExperiment(
      assays = list(mat_otu),
      colData = df_metadata
    )
    
    start_time <- Sys.time()
    fit.BDMMA <- BDMMAcorrect::BDMMA(Microbiome_dat = sSet)
    
    return(Sys.time() - start_time)
  }
) 
doParallel::stopImplicitCluster()
save(times_BDMMA, file = paste0(dir_output, "time_BDMMA.RData"))
```