---
title: "2.1-Check metadata"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    df_print: paged
---
# Overview
- Check the availability of metadata across studies
```{r setup, echo=FALSE}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```
```{r setup2, echo=FALSE}
rm(list = ls())
for(i.function in list.files("functions/", full.names = TRUE)) {
  source(i.function)
}
setup(getwd())
dir_output <- "results/2.1-check_metadata/"
dir.create(dir_output, recursive = TRUE, showWarnings = FALSE)
```

# Metadata filtering
```{r filtering}
load("data/phyloseq/genera.RData")
load("data/phyloseq/species.RData")
phylo_genera <- phylo_genera %>% 
  phyloseq::subset_samples(libSize >= 3000 &
                             disease %in% c("CD", "UC", "control") &
                             !is.na(sample_type) &
                             !(dataset_name %in% "Pouchitis" & disease %in% "CD"))
phylo_species <- phylo_species %>% 
  phyloseq::prune_samples(phyloseq::sample_names(phylo_genera), .)
# add baseline variable
metadata <- sample_data2(phylo_genera)
metadata_HMP2 <- metadata %>% 
  dplyr::filter(dataset_name == "HMP2") %>% 
  dplyr::mutate(time_point2 = as.numeric(time_point)) %>% 
  dplyr::group_by(subject_accession) %>% 
  dplyr::arrange(time_point2) %>% 
  dplyr::mutate(is_baseline = time_point2 %in% time_point2[1]) %>% 
  dplyr::select(-time_point2)
metadata_PROTECT <- metadata %>% 
  dplyr::filter(dataset_name == "PROTECT") %>% 
  dplyr::mutate(time_point2 = as.numeric(time_point)) %>% 
  dplyr::group_by(subject_accession) %>% 
  dplyr::arrange(time_point2) %>% 
  dplyr::mutate(is_baseline = time_point2 %in% time_point2[1]) %>% 
  dplyr::select(-time_point2)
metadata_LSS_PRISM <- metadata %>% 
  dplyr::filter(dataset_name == "LSS-PRISM") %>% 
  dplyr::mutate(time_point2 = as.numeric(time_point)) %>% 
  dplyr::group_by(subject_accession) %>% 
  dplyr::arrange(time_point2) %>% 
  dplyr::mutate(is_baseline = time_point2 %in% time_point2[1]) %>% 
  dplyr::select(-time_point2)
metadata_Jansson <- metadata %>% 
  dplyr::filter(dataset_name == "Jansson_Lamendella_Crohns") %>% 
  dplyr::mutate(time_point2 = time_point %>% 
                  stringr::str_replace_all("\\:.*$", "") %>% 
                  as.numeric) %>% 
  dplyr::group_by(subject_accession) %>% 
  dplyr::arrange(time_point2) %>% 
  dplyr::mutate(is_baseline = time_point2 %in% time_point2[1]) %>% 
  dplyr::select(-time_point2)
metadata_Herfarth <- metadata %>% 
  dplyr::filter(dataset_name == "Herfarth_CCFA_Microbiome_3B_combined") %>% 
  dplyr::mutate(time_point2 = as.Date(time_point, format = "%Y-%m-%d")) %>% 
  dplyr::group_by(subject_accession) %>% 
  dplyr::arrange(time_point2) %>% 
  dplyr::mutate(is_baseline = time_point2 %in% time_point2[1]) %>% 
  dplyr::select(-time_point2)
metadata <- rbind(metadata_HMP2,
                  metadata_PROTECT,
                  metadata_LSS_PRISM,
                  metadata_Jansson,
                  metadata_Herfarth) %>% 
  dplyr::right_join(metadata, by = colnames(metadata)) %>% 
  dplyr::mutate(is_baseline = ifelse(is.na(is_baseline),
                                     FALSE,
                                     is_baseline))
rownames(metadata) <- metadata$sample_accession_16S
all(rownames(metadata) == sample_names(phylo_genera))
sample_data(phylo_genera) <- metadata
sample_data(phylo_species) <- metadata
any(phyloseq::sample_sums(phylo_genera) == 0)
any(phyloseq::sample_sums(phylo_species) == 0)
any(phyloseq::taxa_sums(phylo_genera) == 0)
any(phyloseq::taxa_sums(phylo_species) == 0)
save(phylo_genera, file = "data/phyloseq/genera.RData")
save(phylo_species, file = "data/phyloseq/species.RData")
```


# Availability of metadata
```{r check availability}
template <- readr::read_csv(paste0(dir_processed, "data/template.csv"))
df_metadata <- sample_data2(phylo_genera)
df_metaLong <- df_metadata %>% 
  dplyr::select(-(study_accession:alternative_sample_accession),
                -sample_accession_WGS, -site,
                -(extraction_kit_16S:median_read_length_16S)) %>% 
  tidyr::gather(key = variable, value = value, -dataset_name, -sample_accession_16S) %>% 
  dplyr::left_join(template, by = c("variable" = "col.name")) %>% 
  dplyr::mutate(variable = factor(variable, levels = template$col.name))
df_avail <- df_metaLong %>% 
  dplyr::group_by(dataset_name, variable) %>% 
  dplyr::summarise(is_available = any(!is.na(value)))
df_avail %>% 
  ggplot(aes(x = dataset_name, y = variable, fill = is_available)) + geom_tile() +
  scale_fill_manual(values = c("TRUE" = "black", "FALSE" = "white")) + rotate_xaxis(15)
ggsave(file = paste0(dir_output, "fig_checkAvailabbility.pdf"),
       width = 10, height = 10)
```
# Distribution of metadata
```{r distribution of metadata}
df_metaLong <- df_metaLong %>% dplyr::left_join(df_avail, by = c("dataset_name", "variable"))
l_p_disc <- df_metaLong %>% 
  dplyr::filter(var.class == "character", allowedvalues != "*") %>% 
  dplyr::mutate(value_mod = ifelse(!is_available, 
                                   NA,
                                   dplyr::recode(value, .missing = "not available"))) %>% 
  dplyr::group_by(variable) %>% 
  tidyr::nest() %>% 
  dplyr::mutate(p = purrr::map2(variable, data, function(variable, idf) {
    levels_value <- idf$allowedvalues %>% unique() %>% 
      strsplit("|", fixe = TRUE) %>% extract2(1)
    colors_value <- gg_color_hue(levels_value)
    idf %>% 
      dplyr::mutate(value_mod = value_mod %>% 
                      factor(levels = c(levels_value, "not available") %>% 
                               rev)) %>% 
      dplyr::group_by(dataset_name, value_mod) %>% 
      dplyr::summarise(n = sum(!is.na(value_mod))) %>% 
      ggplot(aes(x = dataset_name, y = n, fill = value_mod)) + geom_bar(stat = "identity") +
      scale_fill_manual(values = c(colors_value, "not available" = "darkgray")) +
      ggtitle(variable) + rotate_xaxis(30)
  })) %>% 
  extract2("p")
cowplot::plot_grid(plotlist = l_p_disc, ncol = 2) %>% 
  ggsave(filename = paste0(dir_output, "fig_discDist.pdf"),
         width = 10, height = length(l_p_disc) * 2.5)
l_p_num <- df_metaLong %>% 
  dplyr::filter(var.class == "numeric") %>% 
  dplyr::group_by(variable) %>% 
  tidyr::nest() %>% 
  dplyr::mutate(p = purrr::map2(variable, data, function(variable, idf) {
    idf %>% 
      dplyr::mutate(value = as.numeric(value)) %>% 
      dplyr::group_by(dataset_name) %>% 
      dplyr::mutate(perc_na = mean(is.na(value)) %>% 
                      multiply_by(100) %>% round(2)) %>%
      dplyr::ungroup() %>% 
      ggplot(aes(x = paste0(dataset_name, "\n", perc_na, "% missing"), 
                 y = value)) + 
      geom_violin() + geom_boxplot(width = 0.1) + 
      ggtitle(variable) + xlab("dataset_name") + rotate_xaxis(30)
  })) %>% 
  extract2("p")
cowplot::plot_grid(plotlist = l_p_num, ncol = 1) %>% 
  ggsave(filename = paste0(dir_output, "fig_numDist.pdf"),
         width = 8, height = length(l_p_num) * 4)
```

