---
title: "3-non unique taxa"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
---
# Overview
- How sensitive are the ordinations etc. after subsetting to non-unique taxa?

```{r setup, echo = FALSE}
knitr::opts_knit$set(root.dir = normalizePath(".."))
```
```{r setup2, message=FALSE, warning=FALSE, echo = FALSE}
rm(list = ls())
for(i.function in list.files("functions/", full.names = TRUE)) {
  source(i.function)
}
setup(getwd())
dir_output <- "results/3.1-non_unique_taxa/"
dir.create(dir_output, recursive = TRUE, showWarnings = FALSE)
```
# Load datasets
```{r calculate distance and ordination}
print(studies)
tb_filter <- readr::read_tsv("results/2-QC/filter.tsv") %>% 
  dplyr::filter(cutoff_abundance == 1e-4, cutoff_prevalence == 0.05,
                n_study >= 2) %>% 
  dplyr::rename(feature_level_all = feature_level)
n_permutations <- 2 # set # permuations for PERMANOVA
for(feature_level in c("genera", "species")) {
  load(paste0("data/phyloseq/", feature_level, ".Rdata"))
  load(paste0("data/phyloseq/", feature_level, "_adj.Rdata"))
  phylo <- get(paste0("phylo_", feature_level)) %>% 
    phyloseq::prune_taxa(tb_filter %>% 
                           dplyr::filter(feature_level_all == feature_level) %>% 
                           dplyr::pull(feature), .)
  phylo_adj <- get(paste0("phylo_", feature_level, "_adj")) %>% 
    phyloseq::prune_taxa(tb_filter %>% 
                           dplyr::filter(feature_level_all == feature_level) %>% 
                           dplyr::pull(feature), .)
  
  # calculate distance
  distance <- phylo %>%
    to_relativeAbundance() %>%
    phyloseq::distance(method = "bray")
  assign(paste0("dist_", feature_level), distance)
  save(list = paste0("dist_", feature_level),
       file = paste0(dir_output, "dist_", feature_level, ".RData"))
  distance_adj <- phylo_adj %>%
    to_relativeAbundance() %>%
    phyloseq::distance(method = "bray")
  assign(paste0("dist_", feature_level, "_adj"), distance_adj)
  save(list = paste0("dist_", feature_level, "_adj"),
       file = paste0(dir_output, "dist_", feature_level, "_adj.RData"))
  
  # ordination
  ordinate_before <- ape::pcoa(D = distance)
  ordinate_after <- ape::pcoa(D = distance_adj)
  assign(paste0("ordinate_before_", feature_level), ordinate_before)
  assign(paste0("ordinate_after_", feature_level), ordinate_after)
  save(list = paste0("ordinate_before_", feature_level),
       file = paste0(dir_output, "ordinate_before_", feature_level, ".RData"))
  save(list = paste0("ordinate_after_", feature_level),
       file = paste0(dir_output, "ordinate_after_", feature_level, ".RData"))
}
```

# Ordination figures
```{r ordination}
# A whole bunch of ordination
dir_outputChunk <- paste0(dir_output, "ordination/")
dir.create(dir_outputChunk, recursive = TRUE, showWarnings = TRUE)
n_permutations <- 2
metadata <- sample_data2(phylo_genera)
for(feature_level in c("genera", "species")) {
  dir.create(paste0(dir_outputChunk, feature_level), 
             recursive = TRUE, showWarnings = TRUE)
  phylo <- get(paste0("phylo_", feature_level))
  phylo_adj <- get(paste0("phylo_", feature_level, "_adj"))
  ordinate_before <- get(paste0("ordinate_before_", feature_level))
  ordinate_after <- get(paste0("ordinate_after_", feature_level))
  l_dist <- list(before = get(paste0("dist_", feature_level)), 
                 after = get(paste0("dist_", feature_level, "_adj")))
  l_fit_adonis <- l_dist %>% 
    purrr::map(~vegan::adonis(. ~ dataset_name, data = metadata, 
                              permutations = n_permutations))  
  l_fit_adonisCond <- l_dist %>% 
    purrr::map(~vegan::adonis(. ~ disease + body_site + dataset_name, 
                              data = metadata, 
                              permutations = n_permutations))  
  list(1:2, 3:4) %>% 
    purrr::walk(function(axes) {
      # study
      colors_study <- c("RISK" = "black",
                        "PROTECT" = "grey",
                        gg_color_hue(values = setdiff(studies, 
                                                      c("RISK", "PROTECT"))))
      p1 <- phyloseq::plot_ordination(phylo, 
                                      ordinate_before, 
                                      axes = axes,
                                      color = "dataset_name") +
        scale_color_manual(values = colors_study) +
        ggtitle(paste0("Before R2=", 
                       round(l_fit_adonis$before$aov.tab["dataset_name", 
                                                         "R2"] * 100, 
                             digits = 2),
                       "\n",
                       "conditional R2=",
                       round(l_fit_adonisCond$before$aov.tab["dataset_name", 
                                                             "R2"] * 100, 
                             digits = 2)))
      p2 <- phyloseq::plot_ordination(phylo_adj, 
                                      ordinate_after, 
                                      axes = axes,
                                      color = "dataset_name") +
        scale_color_manual(values = colors_study) +
        ggtitle(paste0("After R2=", 
                       round(l_fit_adonis$after$aov.tab["dataset_name", 
                                                        "R2"] * 100, 
                             digits = 2),
                       "\n",
                       "conditional R2=",
                       round(l_fit_adonisCond$after$aov.tab["dataset_name", 
                                                            "R2"] * 100, 
                             digits = 2)))
      cowplot::plot_grid(p1, p2, nrow = 1) %>% 
        ggsave(filename = paste0(dir_outputChunk, feature_level, "/study", 
                                 paste(axes, collapse = ""),".pdf"),
               width = 15, height = 5)
      
      tb_plot <- metadata %>%
        tibble::rownames_to_column() %>% 
        dplyr::left_join(ordinate_after$vectors[, axes] %>% 
                           as.data.frame %>% 
                           set_colnames(c("x.Axis", "y.Axis")) %>% 
                           tibble::rownames_to_column(), 
                         by = "rowname")
      # disease
      colors_disease <- c(gg_color_hue(c("CD", "UC")), "control" = "black")
      p1 <- tb_plot %>% dplyr::filter(disease %in% c("CD", "UC", "control")) %>% 
        ggplot(aes(x = x.Axis, y = y.Axis, color = disease)) + 
        geom_point() +
        scale_color_manual(values = colors_disease) + 
        ggtitle("Disease") + coord_fixed()
      # p2 <- tb_plot %>% dplyr::filter(disease != "control") %>% 
      #   ggplot(aes(x = x.Axis, y = y.Axis, color = disease)) + geom_point() +
      #   scale_color_manual(values = colors_disease, guide = FALSE)
      # p3 <- tb_plot %>% dplyr::filter(disease != "UC") %>% 
      #   ggplot(aes(x = x.Axis, y = y.Axis, color = disease)) + geom_point() +
      #   scale_color_manual(values = colors_disease, guide = FALSE)
      # p4 <- tb_plot %>% dplyr::filter(disease != "CD") %>% 
      #   ggplot(aes(x = x.Axis, y = y.Axis, color = disease)) + geom_point() +
      #   scale_color_manual(values = colors_disease, guide = FALSE)
      # cowplot::plot_grid(p1, cowplot::plot_grid(p2, p3, p4, ncol = 1), 
      #                    nrow = 1, rel_widths = c(3.5, 1)) %>% 
      #   ggsave(filename = paste0(dir_output, "ordination/disease", 
      #                            paste(axes, collapse = ""),".pdf"),
      #          width = 20, height = 12)
      ggsave(filename = paste0(dir_outputChunk, feature_level, "/disease", 
                               paste(axes, collapse = ""),".pdf"), 
             p1,
             width = 7, height = 6)
      p1 <- tb_plot %>% 
        dplyr::filter(!is.na(L.cat), L.cat %in% c("L1", "L2", "L3")) %>% 
        ggplot(aes(x = x.Axis, y = y.Axis, color = L.cat)) + geom_point() + 
        coord_fixed() + ggtitle("CD location category")
      p2 <- tb_plot %>% 
        dplyr::filter(!is.na(B.cat)) %>% 
        ggplot(aes(x = x.Axis, y = y.Axis, color = B.cat)) + geom_point() + 
        coord_fixed() + ggtitle("CD behaviour category")
      p3 <- tb_plot %>% 
        dplyr::filter(!is.na(E.cat)) %>% 
        ggplot(aes(x = x.Axis, y = y.Axis, color = E.cat)) + geom_point() + 
        coord_fixed() + ggtitle("UC extent cateogry")
      cowplot::plot_grid(p1, p2, p3, nrow = 1) %>% 
        ggsave(filename = paste0(dir_outputChunk, feature_level, 
                                 "/disease_subtype", 
                                 paste(axes, collapse = ""),".pdf"),
               ., width = 17, height = 5)
      
      
      # body site
      p1 <- tb_plot %>% 
        ggplot(aes(x = x.Axis, y = y.Axis, color = sample_type)) + geom_point() + 
        coord_fixed() + ggtitle("biopsy vs. stool")
      p2 <- tb_plot %>% 
        dplyr::filter(sample_type %in% "biopsy") %>% 
        ggplot(aes(x = x.Axis, y = y.Axis, color = body_site)) + geom_point() + 
        coord_fixed() + ggtitle("biopsy site")
      cowplot::plot_grid(p1, p2, nrow = 1) %>% 
        ggsave(filename = paste0(dir_outputChunk, feature_level, "/bodysite", 
                                 paste(axes, collapse = ""),".pdf"),
               ., width = 12, height = 5)
      
      # age
      p1 <- tb_plot %>% 
        dplyr::filter(!is.na(age)) %>% 
        ggplot(aes(x = x.Axis, y = y.Axis, color = age <= 18)) + geom_point() + 
        coord_fixed() + ggtitle("age (sample collection)")
      p2 <- tb_plot %>% 
        dplyr::mutate(A.cat = ifelse(!is.na(age_at_diagnosis.cat),
                                     age_at_diagnosis.cat,
                                     dplyr::case_when(
                                       age_at_diagnosis < 16 ~ "A1",
                                       age_at_diagnosis < 40 ~ "A2",
                                       !is.na(age_at_diagnosis) ~ "A3",
                                       TRUE ~ NA_character_
                                     ))) %>% 
        dplyr::filter(!is.na(A.cat)) %>% 
        ggplot(aes(x = x.Axis, y = y.Axis, color = A.cat)) + geom_point() + 
        coord_fixed() + ggtitle("age (diagnosis)")
      cowplot::plot_grid(p1, p2, nrow = 1) %>% 
        ggsave(filename = paste0(dir_outputChunk, feature_level, "/age", 
                                 paste(axes, collapse = ""),".pdf"),
               ., width = 12, height = 5)
      
      # treatment
      colors_treatment <- gg_color_hue(c("y", "n"))
      l_p <- c("CD", "UC") %>% 
        purrr::map(function(i_disease) {
          c("antibiotics", "immunosuppressants", 
            "steroids", "mesalamine_5ASA") %>% 
            purrr::map(function(i_treatment) {
              tb_plot %>% 
                dplyr::filter(disease == i_disease, 
                              !is.na(!!rlang::sym(i_treatment))) %>% 
                ggplot(aes(x = x.Axis, y = y.Axis, 
                           color = !!rlang::sym(i_treatment))) +
                geom_point() + coord_fixed() + 
                ggtitle(paste0(i_disease, ", ", i_treatment)) +
                scale_color_manual(values = colors_treatment)
            })
        }) %>% purrr::reduce(c)
      cowplot::plot_grid(plotlist = l_p, nrow = 2) %>% 
        ggsave(filename = paste0(dir_outputChunk, feature_level, 
                                 "/treatment", 
                                 paste(axes, collapse = ""),".pdf"),
               ., width = 20, height = 8)
    })
}
```