---
title: "4-association"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
html_document:
df_print: paged
---
# Overview
Perform association analysis on covariates.
- PERMANOVA
- Maaslin2

```{r setup, echo = FALSE}                                           
knitr::opts_knit$set(root.dir = normalizePath(".."))
```
```{r setup2, message=FALSE, warning=FALSE, echo = FALSE}
rm(list = ls())
for(i.function in list.files("functions/", full.names = TRUE)) {
  source(i.function)
}
setup(getwd())
dir_output <- "results/4-association/"
dir.create(dir_output, recursive = TRUE, showWarnings = FALSE)
```
# PERMANOVA
```{r PERMANOVA}
print(studies)
dir_outputChunk <- paste0(dir_output, "PERMANOVA/")
dir.create(dir_outputChunk)
load("data/phyloseq/genera_adj.RData")
load("data/distance/dist_genera_adj.RData")
n_permutations <- 999 # set # permuations for PERMANOVA

metadata <- sample_data2(phylo_genera_adj)
# manipulate variables to test, so that avoid missing values
metadata_test <- metadata %>% 
  dplyr::mutate(B.cat_fill = fill_na(B.cat),
                L.cat_fill = fill_na(L.cat),
                E.cat_fill = fill_na(E.cat),
                race_fill = fill_na(race),
                gender_fill = fill_na(gender),
                age.cat_fill = 
                  dplyr::case_when(age < 18 ~ "child",
                                   !is.na(age) ~ "adult",
                                   TRUE ~ NA_character_) %>% fill_na,
                age_at_diagnosis.cat_fill = 
                  dplyr::case_when(age_at_diagnosis < 18 ~ "A1",
                                   age_at_diagnosis < 40 ~ "A2",
                                   !is.na(age_at_diagnosis) ~ "A3",
                                   TRUE ~ NA_character_) %>% fill_na,
                antibiotics_fill = fill_na(antibiotics),
                immunosuppressants_fill = fill_na(immunosuppressants),
                steroids_fill = fill_na(steroids),
                mesalamine_5ASA_fill = fill_na(mesalamine_5ASA))

# whole bunch of PERMANOVA fits
# l_fit_adonisMarg <- paste0(c("race", 
#                              "gender", 
#                              "age.cat", 
#                              "age_at_diagnosis.cat"), "_fill") %>% 
#   purrr::map(function(variable) {
#     as.formula(paste0("dist_genera_adj~(", variable,
#                       "==\"NA\")", "+", variable)) %>% 
#       vegan::adonis(data = metadata_test, permutations = n_permutations)
#   })
# save(l_fit_adonisMarg, file = paste0(dir_outputChunk, "l_fit_adonisMarg.RData"))
load(paste0(dir_outputChunk, "l_fit_adonisMarg.RData"))
# l_fit_adonisCond <- paste0(c("B.cat", "L.cat", "E.cat", 
#                              "antibiotics",
#                              "immunosuppressants",
#                              "steroids",
#                              "mesalamine_5ASA"), "_fill") %>% 
#   purrr::map(function(variable) {
#     as.formula(paste0("dist_genera_adj~disease+(", variable,
#                       "==\"NA\")", "+", variable)) %>% 
#       vegan::adonis(data = metadata_test, permutations = n_permutations)
#   })
# save(l_fit_adonisCond, file = paste0(dir_outputChunk, "l_fit_adonisCond.RData"))
load(paste0(dir_outputChunk, "l_fit_adonisCond.RData"))
# fit_adonis_disease <- 
#   vegan::adonis(dist_genera_adj~disease,
#                 data = metadata_test, permutations = n_permutations)
# save(fit_adonis_disease, file = paste0(dir_outputChunk, "fit_adonis_disease.RData"))
load(paste0(dir_outputChunk, "fit_adonis_disease.RData"))
# fit_adonis_bodySite <- 
#   vegan::adonis(dist_genera_adj~sample_type + body_site,
#                 data = metadata_test, permutations = n_permutations)
# save(fit_adonis_bodySite, file = paste0(dir_outputChunk, "fit_adonis_bodySite.RData"))
load(paste0(dir_outputChunk, "fit_adonis_bodySite.RData"))
# fit_adonis_subject <- 
#   vegan::adonis(dist_genera_adj~dataset_name + subject_accession,
#                 data = metadata_test, permutations = n_permutations)
# save(fit_adonis_subject, file = paste0(dir_outputChunk, "fit_adonis_subject.RData"))
load(paste0(dir_outputChunk, "fit_adonis_subject.RData"))
tb_marg <- c("race", 
             "gender", 
             "age.cat", 
             "age_at_diagnosis.cat") %>% 
  purrr::map2_dfr(l_fit_adonisMarg, function(variable, i_fit_adonis) {
    tibble::tibble(R2 = i_fit_adonis$aov.tab$R2[1:2],
                   pval = i_fit_adonis$aov.tab$`Pr(>F)`[1:2],
                   variable = variable,
                   is_NA = c("is_NA", "non_missing"))
  })
tb_cond <-c("B.cat", "L.cat", "E.cat", 
            "antibiotics",
            "immunosuppressants",
            "steroids",
            "mesalamine_5ASA") %>% 
  purrr::map2_dfr(l_fit_adonisCond, function(variable, i_fit_adonis) {
    tibble::tibble(R2 = i_fit_adonis$aov.tab$R2[2:3],
                   pval = i_fit_adonis$aov.tab$`Pr(>F)`[2:3],
                   variable = variable,
                   is_NA = c("is_NA", "non_missing"))
  })
tb_disease <- tibble::tibble(R2 = fit_adonis_disease$aov.tab$R2[1], 
                             pval = fit_adonis_disease$aov.tab$`Pr(>F)`[1],
                             variable = "disease", is_NA = "non_missing")
tb_bodySite <- tibble::tibble(R2 = fit_adonis_bodySite$aov.tab$R2[1:2], 
                              pval = fit_adonis_bodySite$aov.tab$`Pr(>F)`[1:2], 
                              variable = c("stool/biopsy", "biopsy_site"), 
                              is_NA = "non_missing")
tb_subject <- tibble::tibble(R2 = fit_adonis_subject$aov.tab$R2[1:2],
                             pval = fit_adonis_subject$aov.tab$`Pr(>F)`[1:2],
                             variable = c("study", "subject"),
                             is_NA = "non_missing")
tb_plot <- rbind(tb_bodySite, tb_marg, tb_disease, tb_cond, tb_subject) %>% 
  dplyr::mutate(variable = factor(variable, levels = rev(unique(variable))),
                is_NA = factor(is_NA, levels = c("non_missing", "is_NA"))) %>% 
  dplyr::mutate(p_levels = 
                  dplyr::case_when(
                    pval <= 0.001 ~ "***",
                    pval <= 0.01 ~ "**",
                    pval <= 0.05 ~ "*",
                    TRUE ~ ""
                  ))
tb_plot %>% 
  ggplot(aes(x = is_NA, y = variable, fill = R2)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "black", trans = "log10") +
  geom_text(aes(label = paste0(round(R2*100, digits = 2), "%\n",
                               p_levels)), 
            color = "red")
ggsave(filename = paste0(dir_outputChunk, "PERMANOVA.pdf"), width = 5, height = 8)
```
# Maaslin2
```{r Maaslin2}
dir_outputChunk <- paste0(dir_output, "Maaslin2/")
dir.create(dir_outputChunk)
source("assets/ma_tests.R")

metadata_test <- metadata %>% 
  dplyr::mutate(race_fill = fill_na(race),
                gender_fill = fill_na(gender),
                age.cat_fill = 
                  dplyr::case_when(age < 18 ~ "child",
                                   !is.na(age) ~ "adult",
                                   TRUE ~ NA_character_) %>% fill_na,
                age_at_diagnosis.cat_fill = 
                  dplyr::case_when(age_at_diagnosis < 18 ~ "A1",
                                   age_at_diagnosis < 40 ~ "A2",
                                   !is.na(age_at_diagnosis) ~ "A3",
                                   TRUE ~ NA_character_) %>% fill_na,
                study_site = paste(dataset_name, 
                                   sample_type, 
                                   sep = "_"),
                study_site_disease = paste0(dataset_name, 
                                            sample_type, 
                                            disease, sep = "_"),
                subject_accession_longitudinal =
                  ifelse(dataset_name %in%
                           studies_longitudinal,
                         subject_accession,
                         NA_character_))

for(feature_level in c("genera", "species", "otus")) {
  dir.create(paste0(dir_outputChunk, feature_level, "/"))
  load(paste0("data/phyloseq/", feature_level, "_adj.RData"))
  mat_otu_adj <- get(paste0("phylo_", feature_level, "_adj")) %>% 
    transform_sample_counts(tss) %>%  
    otu_table2
  
  l_results <- list()
  for(test in names(l_tests)) {
    print(test)
    test_param <- l_tests[[test]]
    result <- fit_metaAnalysis(mat_otu = mat_otu_adj,
                               data = metadata_test %>%
                                 dplyr::filter(!!test_param$exprs_filter),
                               test_variable = test_param$test_variable,
                               contrasts = test_param$contrasts,
                               batch_variable = test_param$batch_variable,
                               covariates = test_param$covariates,
                               covariates.random = 
                                 test_param$covariates.random,
                               moderator_variables =
                                 test_param$moderator_variables,
                               n_features = 50,
                               normalization = "TSS",
                               transform = "AST",
                               analysis_method = "LM",
                               rma_method = "REML",
                               directory = paste0(dir_outputChunk, 
                                                  feature_level, "/",
                                                  test, "/"),
                               forest.plots = TRUE,
                               verbose = FALSE)
    save(result, file = paste0(dir_outputChunk, feature_level, "/",
                               test, "/result.RData"))
    # load(paste0(dir_outputChunk, feature_level, "/",
    #             test, "/result.RData"))
    l_results[[test]] <- result
  }
  result_all <- l_results %>% 
    purrr::imap_dfr(function(result, test) {
      result$tb_summarise %>% 
        tidyr::gather(key = study, value = weight, dplyr::matches("weight_")) %>% 
        dplyr::group_by_at(vars(-weight, -study)) %>% 
        dplyr::arrange(desc(weight)) %>% 
        dplyr::summarise(max_weight = weight[1],
                         study_max_weight = study[1]) %>% 
        dplyr::ungroup() %>% 
        dplyr::mutate(study_max_weight = study_max_weight %>% 
                        stringr::str_replace_all("weight\\_", ""),
                      test = test,
                      q.fdr_meta = ifelse(k > 2,
                                          pval,
                                          NA_real_) %>% 
                        p.adjust(method = "fdr"))
    })
  readr::write_tsv(result_all, paste0(dir_outputChunk, 
                                      feature_level,
                                      "/all_results.tsv"))
  
  # Visualization
  # disease status
  i_tests <- c("CD_vs_control", "UC_vs_control", "CD_vs_UC")
  plot_metaAnalysis(l_results, i_tests, "disease_status", 
                    paste0(dir_outputChunk, feature_level, "/"))
  # disease subtype
  i_tests <- c("L2_vs_L1", "L3_vs_L1", "L4", "B2_vs_B1", "B3_vs_B1", 
               "E2_vs_E1", "E3_vs_E1", "A2_vs_A1", "A3_vs_A1")
  plot_metaAnalysis(l_results, i_tests, "disease_subtype", 
                    paste0(dir_outputChunk, feature_level, "/"))
  # treatment
  i_tests <- c("antibiotics", "immunosuppressants", "steroids", "mesalamine_5ASA")
  plot_metaAnalysis(l_results, i_tests, "treatment", 
                    paste0(dir_outputChunk, feature_level, "/"))
  # covariates
  i_tests <- c("age", "gender")
  plot_metaAnalysis(l_results, i_tests, "covariates", 
                    paste0(dir_outputChunk, feature_level, "/"))
}
```
# Compare OTU-level and species-level Maaslin2 results
```{r Maaslin2 OTU vs. species}
dir_outputChunk <- paste0(dir_output, "Maaslin2/species_vs_otus/")
dir.create(dir_outputChunk)
l_results_species <- l_results_otus <- list()
for(test in names(l_tests)) {
  print(test)
  test_param <- l_tests[[test]]
  # result <- fit_metaAnalysis(mat_otu = mat_otu_adj,
  #                            data = metadata_test %>%
  #                              dplyr::filter(!!test_param$exprs_filter),
  #                            test_variable = test_param$test_variable,
  #                            contrasts = test_param$contrasts,
  #                            batch_variable = test_param$batch_variable,
  #                            covariates = test_param$covariates,
  #                            covariates.random = 
  #                              test_param$covariates.random,
  #                            moderator_variables =
  #                              test_param$moderator_variables,
  #                            n_features = 50,
  #                            normalization = "TSS",
  #                            transform = "AST",
  #                            analysis_method = "LM",
  #                            rma_method = "REML",
  #                            directory = paste0(dir_outputChunk, 
  #                                               feature_level, "/",
  #                                               test, "/"),
  #                            forest.plots = TRUE,
  #                            verbose = FALSE)
  # save(result, file = paste0(dir_outputChunk, feature_level, "/",
  #                            test, "/result.RData"))
  load(paste0("results/4-association/Maaslin2/species/",
              test, "/result.RData"))
  l_results_species[[test]] <- result
  load(paste0("results/4-association/Maaslin2/otus/",
              test, "/result.RData"))
  l_results_otus[[test]] <- result
}
tb_species <- l_results_species %>% 
  purrr::imap_dfr(function(result, test) {
    result$tb_summarise %>% 
      dplyr::filter(k >= 2) %>% 
      dplyr::transmute(feature_species = feature, 
                       beta_species = beta, 
                       se_species = se, 
                       pval_species = pval) %>% 
      dplyr::mutate(q.fdr_species = p.adjust(pval_species, method = "fdr")) %>% 
      dplyr::mutate(test = test)
  })
tb_otus <- l_results_otus %>% 
  purrr::imap_dfr(function(result, test) {
    result$tb_summarise %>% 
      dplyr::filter(k >= 2) %>% 
      dplyr::select(feature, 
                    beta, 
                    se, 
                    pval) %>% 
      dplyr::mutate(q.fdr = p.adjust(pval, method = "fdr")) %>% 
      dplyr::mutate(test = test)
  }) %>% 
  dplyr::mutate(feature_species = feature %>% 
                  stringr::str_replace_all("\\|\\d+$", "") %>% 
                  paste0("|NA"))
tb_plot <- tb_otus %>% 
  left_join(tb_species, by = c("test", "feature_species")) %>% 
  dplyr::group_by(feature_species, test) %>% 
  dplyr::mutate(n_otus = n(),
                q.fdr_min = min(q.fdr)) %>% 
  dplyr::ungroup()
p <- tb_plot %>% 
  dplyr::filter(q.fdr_min <= 0.05 | q.fdr_species <= 0.05,
                n_otus > 1,
                test %in% ("CD_vs_control")) %>% 
  ggplot(aes(x = feature_species, y = beta)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(aes(color = q.fdr < 0.05), position = position_jitter(width = 0.25)) +
  geom_point(aes(x = feature_species, y = beta_species, color = q.fdr_species < 0.05), 
             shape = 17, size = 3) +
  scale_color_manual(values = c("TRUE" = "red", "FALSE" = "black")) +
  coord_flip()
ggsave(paste0(dir_outputChunk, "CD_vs_control.pdf"),
       p,
       height = tb_plot %>% 
         dplyr::filter(q.fdr_min <= 0.05 | q.fdr_species <= 0.05,
                n_otus > 1,
                test %in% ("CD_vs_control")) %>% 
         dplyr::pull(feature_species) %>% 
         unique %>% length %>% divide_by(4),
       width = 15)
```

# Effect modification of sample type / disease status?
```{r Maaslin2 OTU vs. species}
dir_outputChunk <- paste0(dir_output, "Maaslin2/effect_modification/")
dir.create(dir_outputChunk)
l_results_genera <- l_results_species <- l_results_otus <- list()
for(test in names(l_tests)) {
  print(test)
  test_param <- l_tests[[test]]
  # result <- fit_metaAnalysis(mat_otu = mat_otu_adj,
  #                            data = metadata_test %>%
  #                              dplyr::filter(!!test_param$exprs_filter),
  #                            test_variable = test_param$test_variable,
  #                            contrasts = test_param$contrasts,
  #                            batch_variable = test_param$batch_variable,
  #                            covariates = test_param$covariates,
  #                            covariates.random = 
  #                              test_param$covariates.random,
  #                            moderator_variables =
  #                              test_param$moderator_variables,
  #                            n_features = 50,
  #                            normalization = "TSS",
  #                            transform = "AST",
  #                            analysis_method = "LM",
  #                            rma_method = "REML",
  #                            directory = paste0(dir_outputChunk, 
  #                                               feature_level, "/",
  #                                               test, "/"),
  #                            forest.plots = TRUE,
  #                            verbose = FALSE)
  # save(result, file = paste0(dir_outputChunk, feature_level, "/",
  #                            test, "/result.RData"))
  load(paste0("results/4-association/Maaslin2/genera/",
              test, "/result.RData"))
  l_results_genera[[test]] <- result
  load(paste0("results/4-association/Maaslin2/species/",
              test, "/result.RData"))
  l_results_species[[test]] <- result
  load(paste0("results/4-association/Maaslin2/otus/",
              test, "/result.RData"))
  l_results_otus[[test]] <- result
}
tb_genera <- l_results_genera[c("antibiotics",
                                "steroids",
                                "mesalamine_5ASA")] %>% 
  purrr::imap_dfr(function(result, test) {
    result$tb_summarise %>% 
      dplyr::filter(k >= 2) %>% 
      dplyr::select(feature, 
                    beta, 
                    se, 
                    pval,
                    `p.moderator_sample_type+disease`) %>% 
      dplyr::mutate(q.fdr = p.adjust(pval, method = "fdr")) %>% 
      dplyr::mutate(test = test)
  })
tb_genera %>% 
  dplyr::filter(q.fdr < 0.05,
                `p.moderator_sample_type+disease` < 0.05) %>% 
  View
tb_otus <- l_results_otus[c("antibiotics",
                                "steroids",
                                "mesalamine_5ASA")] %>% 
  purrr::imap_dfr(function(result, test) {
    result$tb_summarise %>% 
      dplyr::filter(k >= 2) %>% 
      dplyr::select(feature, 
                    beta, 
                    se, 
                    pval,
                    `p.moderator_sample_type+disease`) %>% 
      dplyr::mutate(q.fdr = p.adjust(pval, method = "fdr")) %>% 
      dplyr::mutate(test = test)
  })
tb_otus %>% 
  dplyr::filter(q.fdr < 0.05 & `p.moderator_sample_type+disease` < 0.05) %>% 
  View
tb_plot <- tb_otus %>% 
  left_join(tb_species, by = c("test", "feature_species")) %>% 
  dplyr::group_by(feature_species, test) %>% 
  dplyr::mutate(n_otus = n(),
                q.fdr_min = min(q.fdr)) %>% 
  dplyr::ungroup()
p <- tb_plot %>% 
  dplyr::filter(q.fdr_min <= 0.05 | q.fdr_species <= 0.05,
                n_otus > 1,
                test %in% ("CD_vs_control")) %>% 
  ggplot(aes(x = feature_species, y = beta)) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(aes(color = q.fdr < 0.05), position = position_jitter(width = 0.25)) +
  geom_point(aes(x = feature_species, y = beta_species, color = q.fdr_species < 0.05), 
             shape = 17, size = 3) +
  scale_color_manual(values = c("TRUE" = "red", "FALSE" = "black")) +
  coord_flip()
ggsave(paste0(dir_outputChunk, "CD_vs_control.pdf"),
       p,
       height = tb_plot %>% 
         dplyr::filter(q.fdr_min <= 0.05 | q.fdr_species <= 0.05,
                n_otus > 1,
                test %in% ("CD_vs_control")) %>% 
         dplyr::pull(feature_species) %>% 
         unique %>% length %>% divide_by(4),
       width = 15)
```
