---
title: "4.1-association_sensitivity"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
html_document:
df_print: paged
---
# Overview
Sensitivity analysis of associations (before batch adjustment).
- PERMANOVA
- Maaslin2

```{r setup, echo = FALSE}                                           
knitr::opts_knit$set(root.dir = normalizePath(".."))
```
```{r setup2, message=FALSE, warning=FALSE, echo = FALSE}
rm(list = ls())
for(i.function in list.files("functions/", full.names = TRUE)) {
  source(i.function)
}
setup(getwd())
dir_output <- "results/4-association/sensitivity/"
dir.create(dir_output, recursive = TRUE, showWarnings = FALSE)
```

# PERMANOVA
```{r PERMANOVA}
print(studies)
dir_outputChunk <- paste0(dir_output, "PERMANOVA/")
dir.create(dir_outputChunk)
load("data/phyloseq/genera.RData")
load("data/distance/dist_genera.RData")
n_permutations <- 2 # set # permuations for PERMANOVA

metadata <- sample_data2(phylo_genera)
# manipulate variables to test, so that avoid missing values
metadata_test <- metadata %>% 
  dplyr::mutate(B.cat_fill = fill_na(B.cat),
                L.cat_fill = fill_na(L.cat),
                E.cat_fill = fill_na(E.cat),
                race_fill = fill_na(race),
                gender_fill = fill_na(gender),
                age.cat_fill = 
                  dplyr::case_when(age < 18 ~ "child",
                                   !is.na(age) ~ "adult",
                                   TRUE ~ NA_character_) %>% fill_na,
                age_at_diagnosis.cat_fill = 
                  dplyr::case_when(age_at_diagnosis < 18 ~ "A1",
                                   age_at_diagnosis < 40 ~ "A2",
                                   !is.na(age_at_diagnosis) ~ "A3",
                                   TRUE ~ NA_character_) %>% fill_na,
                antibiotics_fill = fill_na(antibiotics),
                immunosuppressants_fill = fill_na(immunosuppressants),
                steroids_fill = fill_na(steroids),
                mesalamine_5ASA_fill = fill_na(mesalamine_5ASA))

# whole bunch of PERMANOVA fits
l_fit_adonisMarg <- paste0(c("race",
                             "gender",
                             "age.cat",
                             "age_at_diagnosis.cat"), "_fill") %>%
  purrr::map(function(variable) {
    as.formula(paste0("dist_genera~(", variable,
                      "==\"NA\")", "+", variable)) %>%
      vegan::adonis(data = metadata_test, permutations = n_permutations)
  })
save(l_fit_adonisMarg, file = paste0(dir_outputChunk, "l_fit_adonisMarg.RData"))
# load(paste0(dir_outputChunk, "l_fit_adonisMarg.RData"))
l_fit_adonisCond <- paste0(c("B.cat", "L.cat", "E.cat",
                             "antibiotics",
                             "immunosuppressants",
                             "steroids",
                             "mesalamine_5ASA"), "_fill") %>%
  purrr::map(function(variable) {
    as.formula(paste0("dist_genera~disease+(", variable,
                      "==\"NA\")", "+", variable)) %>%
      vegan::adonis(data = metadata_test, permutations = n_permutations)
  })
save(l_fit_adonisCond, file = paste0(dir_outputChunk, "l_fit_adonisCond.RData"))
# load(paste0(dir_outputChunk, "l_fit_adonisCond.RData"))
fit_adonis_disease <-
  vegan::adonis(dist_genera~disease,
                data = metadata_test, permutations = n_permutations)
save(fit_adonis_disease, file = paste0(dir_outputChunk, "fit_adonis_disease.RData"))
# load(paste0(dir_outputChunk, "fit_adonis_disease.RData"))
fit_adonis_bodySite <-
  vegan::adonis(dist_genera~sample_type + body_site,
                data = metadata_test, permutations = n_permutations)
save(fit_adonis_bodySite, file = paste0(dir_outputChunk, "fit_adonis_bodySite.RData"))
# load(paste0(dir_outputChunk, "fit_adonis_bodySite.RData"))
fit_adonis_subject <-
  vegan::adonis(dist_genera~dataset_name + subject_accession,
                data = metadata_test, permutations = n_permutations)
save(fit_adonis_subject, file = paste0(dir_outputChunk, "fit_adonis_subject.RData"))
# load(paste0(dir_outputChunk, "fit_adonis_subject.RData"))
tb_marg <- c("race",
             "gender",
             "age.cat",
             "age_at_diagnosis.cat") %>%
  purrr::map2_dfr(l_fit_adonisMarg, function(variable, i_fit_adonis) {
    tibble::tibble(R2 = i_fit_adonis$aov.tab$R2[1:2],
                   pval = i_fit_adonis$aov.tab$`Pr(>F)`[1:2],
                   variable = variable,
                   is_NA = c("is_NA", "non_missing"))
  })
tb_cond <-c("B.cat", "L.cat", "E.cat",
            "antibiotics",
            "immunosuppressants",
            "steroids",
            "mesalamine_5ASA") %>%
  purrr::map2_dfr(l_fit_adonisCond, function(variable, i_fit_adonis) {
    tibble::tibble(R2 = i_fit_adonis$aov.tab$R2[2:3],
                   pval = i_fit_adonis$aov.tab$`Pr(>F)`[2:3],
                   variable = variable,
                   is_NA = c("is_NA", "non_missing"))
  })
tb_disease <- tibble::tibble(R2 = fit_adonis_disease$aov.tab$R2[1],
                             pval = fit_adonis_disease$aov.tab$`Pr(>F)`[1],
                             variable = "disease", is_NA = "non_missing")
tb_bodySite <- tibble::tibble(R2 = fit_adonis_bodySite$aov.tab$R2[1:2],
                              pval = fit_adonis_bodySite$aov.tab$`Pr(>F)`[1:2],
                              variable = c("stool/biopsy", "biopsy_site"),
                              is_NA = "non_missing")
tb_subject <- tibble::tibble(R2 = fit_adonis_subject$aov.tab$R2[1:2],
                             pval = fit_adonis_subject$aov.tab$`Pr(>F)`[1:2],
                             variable = c("study", "subject"),
                             is_NA = "non_missing")
tb_plot <- rbind(tb_bodySite, tb_marg, tb_disease, tb_cond, tb_subject) %>%
  dplyr::mutate(variable = factor(variable, levels = rev(unique(variable))),
                is_NA = factor(is_NA, levels = c("non_missing", "is_NA"))) %>%
  dplyr::mutate(p_levels =
                  dplyr::case_when(
                    pval <= 0.001 ~ "***",
                    pval <= 0.01 ~ "**",
                    pval <= 0.05 ~ "*",
                    TRUE ~ ""
                  ))
readr::write_tsv(tb_plot, paste0(dir_outputChunk, "PERMANOVA.tsv"))
tb_plot %>%
  ggplot(aes(x = is_NA, y = variable, fill = R2)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "black", trans = "log10") +
  geom_text(aes(label = paste0(round(R2*100, digits = 2), "%\n",
                               p_levels)),
            color = "red")
ggsave(filename = paste0(dir_outputChunk, "PERMANOVA.pdf"), width = 5, height = 8)
```
# PERMANOVA per study
```{r PERMANOVA per study}
dir_outputChunk <- paste0(dir_output, "PERMANOVA/per_study/")
dir.create(dir_outputChunk, recursive = TRUE, showWarnings = TRUE)
n_permutations <- 2

metadata_test <- metadata_test %>% 
  dplyr::mutate(batch_fill = fill_na(batch))
for(study in studies) {
  print(study)
  dir.create(paste0(dir_outputChunk, study, "/"), 
             recursive = TRUE, showWarnings = TRUE)
  metadata_test_tmp <- subset(metadata_test, dataset_name == study)
  dist_genera_tmp <- subset_distance(dist_genera,
                                     metadata_test$dataset_name == study)
  l_fit_adonisMarg <- paste0(c("race",
                               "gender",
                               "age.cat",
                               "age_at_diagnosis.cat"), "_fill") %>%
    purrr::map(function(variable) {
      if(all(metadata_test_tmp[, variable] == "NA") |
         metadata_test_tmp[, variable] %>% setdiff("NA") %>% 
         length %>% unique %>% is_less_than(2)) return(NULL)
      as.formula(paste0("dist_genera_tmp~(", variable,
                        "==\"NA\")", "+", variable)) %>%
        vegan::adonis(data = metadata_test_tmp, 
                      permutations = n_permutations)
    })
  save(l_fit_adonisMarg, 
       file = paste0(dir_outputChunk, study, "/l_fit_adonisMarg.RData"))
  
  l_fit_adonisCond <- paste0(c("B.cat", "L.cat", "E.cat",
                               "antibiotics",
                               "immunosuppressants",
                               "steroids",
                               "mesalamine_5ASA"), "_fill") %>%
    purrr::map(function(variable) {
      if(all(metadata_test_tmp[, variable] == "NA") |
         metadata_test_tmp[, variable] %>% setdiff("NA") %>% 
         length %>% unique %>% is_less_than(2)) return(NULL)
      if(length(unique(metadata_test_tmp$disease)) < 2) {
        as.formula(paste0("dist_genera_tmp~(", variable,
                          "==\"NA\")", "+", variable)) %>%
          vegan::adonis(data = metadata_test_tmp, 
                        permutations = n_permutations) %>% 
          return()
      } else {
        as.formula(paste0("dist_genera_tmp~disease+(", variable,
                          "==\"NA\")", "+", variable)) %>%
          vegan::adonis(data = metadata_test_tmp, 
                        permutations = n_permutations) %>% 
          return()
      }
    })
  save(l_fit_adonisCond, 
       file = paste0(dir_outputChunk, study, "/l_fit_adonisCond.RData"))
  
  if(length(unique(metadata_test_tmp$disease)) < 2) {
    fit_adonis_disease <- NULL
  } else {
    fit_adonis_disease <-
      vegan::adonis(dist_genera_tmp ~ disease,
                    data = metadata_test_tmp, permutations = n_permutations)
  }
  save(fit_adonis_disease, 
       file = paste0(dir_outputChunk, study, "/fit_adonis_disease.RData"))
  
  if(length(unique(metadata_test_tmp$body_site)) < 2) {
    fit_adonis_bodySite <- NULL
  } else {
    if(all(metadata_test_tmp$sample_type == "biopsy")) {
      fit_adonis_bodySite <-
        vegan::adonis(dist_genera_tmp ~ body_site,
                      data = metadata_test_tmp, permutations = n_permutations)
    } else {
      fit_adonis_bodySite <-
        vegan::adonis(dist_genera_tmp ~ sample_type + body_site,
                      data = metadata_test_tmp, permutations = n_permutations)
    }
  }
  save(fit_adonis_bodySite, 
       file = paste0(dir_outputChunk, study, "/fit_adonis_bodySite.RData"))
  
  fit_adonis_subject <-
    vegan::adonis(dist_genera_tmp ~ subject_accession,
                  data = metadata_test_tmp, permutations = n_permutations)
  save(fit_adonis_subject, 
       file = paste0(dir_outputChunk, study, "/fit_adonis_subject.RData"))
}

tb_plot <- studies %>% 
  purrr::map_dfr(function(study) {
    l_fit_adonisMarg <- get(load(paste0(dir_outputChunk, study, "/l_fit_adonisMarg.RData")))
    tb_marg <- c("race",
                 "gender",
                 "age.cat",
                 "age_at_diagnosis.cat") %>%
      purrr::map2_dfr(l_fit_adonisMarg, function(variable, i_fit_adonis) {
        if(is.null(i_fit_adonis)) {
          tibble::tibble(R2 = NA_real_,
                         pval = NA_real_,
                         variable = variable,
                         is_NA = "non_missing") %>% 
            return()
        } else {
          aov.tab <- i_fit_adonis$aov.tab
          if(nrow(aov.tab) == 4) {
            tibble::tibble(R2 = aov.tab$R2[1:2],
                           pval = aov.tab$`Pr(>F)`[1:2],
                           variable = variable,
                           is_NA = c("is_NA", "non_missing")) %>% 
              return()
          } else {
            tibble::tibble(R2 = aov.tab$R2[1],
                           pval = aov.tab$`Pr(>F)`[1],
                           variable = variable,
                           is_NA = "non_missing") %>% 
              return()
          }
        }
      })
    
    l_fit_adonisCond <- get(load(paste0(dir_outputChunk, study, "/l_fit_adonisCond.RData")))
    tb_cond <-c("B.cat", "L.cat", "E.cat",
                "antibiotics",
                "immunosuppressants",
                "steroids",
                "mesalamine_5ASA") %>%
      purrr::map2_dfr(l_fit_adonisCond, function(variable, i_fit_adonis) {
        if(is.null(i_fit_adonis)) {
          tibble::tibble(R2 = NA_real_,
                         pval = NA_real_,
                         variable = variable,
                         is_NA = "non_missing") %>% 
            return()
        } else {
          aov.tab <- i_fit_adonis$aov.tab
          if("disease" %in% rownames(aov.tab)) aov.tab <- aov.tab[-1, ]
          if(nrow(aov.tab) == 4) {
            tibble::tibble(R2 = aov.tab$R2[1:2],
                           pval = aov.tab$`Pr(>F)`[1:2],
                           variable = variable,
                           is_NA = c("is_NA", "non_missing")) %>% 
              return()
          } else {
            tibble::tibble(R2 = aov.tab$R2[1],
                           pval = aov.tab$`Pr(>F)`[1],
                           variable = variable,
                           is_NA = "non_missing") %>% 
              return()
          }
        }
      })
    
    fit_adonis_disease <- get(load(paste0(dir_outputChunk, study, "/fit_adonis_disease.RData")))
    if(is.null(fit_adonis_disease)) {
      tb_disease <- tibble::tibble(R2 = NA_real_,
                                   pval = NA_real_,
                                   variable = "disease", 
                                   is_NA = "non_missing")
    } else {
      tb_disease <- tibble::tibble(R2 = fit_adonis_disease$aov.tab$R2[1],
                                   pval = fit_adonis_disease$aov.tab$`Pr(>F)`[1],
                                   variable = "disease", is_NA = "non_missing")
    }
    
    fit_adonis_bodySite <- get(load(paste0(dir_outputChunk, study, "/fit_adonis_bodySite.RData")))
    if(is.null(fit_adonis_bodySite)) {
      tb_bodySite <- tibble::tibble(R2 = NA_real_,
                                    pval = NA_real_,
                                    variable = c("stool/biopsy", "biopsy_site"), 
                                    is_NA = "non_missing")
    } else {
      aov.tab <- fit_adonis_bodySite$aov.tab
      if(nrow(aov.tab) == 4) {
        tb_bodySite <- tibble::tibble(R2 = aov.tab$R2[1:2],
                                      pval = aov.tab$`Pr(>F)`[1:2],
                                      variable = c("stool/biopsy", "biopsy_site"),
                                      is_NA = "non_missing")
      } else {
        tb_bodySite <- tibble::tibble(R2 = aov.tab$R2[1],
                                      pval = aov.tab$`Pr(>F)`[1],
                                      variable = c("biopsy_site"),
                                      is_NA = "non_missing")
      }
    }
    
    fit_adonis_subject <- get(load(paste0(dir_outputChunk, study, "/fit_adonis_subject.RData")))
    tb_subject <- tibble::tibble(R2 = fit_adonis_subject$aov.tab$R2[1],
                                 pval = fit_adonis_subject$aov.tab$`Pr(>F)`[1],
                                 variable = c("subject"),
                                 is_NA = "non_missing")
    
    return(rbind(tb_bodySite, tb_marg, 
                 tb_disease, tb_cond, 
                 tb_subject) %>% 
             dplyr::mutate(study = study))
  })
tb_batch <- readr::read_tsv("results/3-adjust_batch/batches/genera/R2_summary.tsv") %>% 
  dplyr::filter(adjust == "before") %>% 
  dplyr::transmute(R2 = R2,
                   pval = Pval,
                   variable = "batch",
                   is_NA = "non_missing",
                   study = study)
tb_plot <- rbind(tb_plot, tb_batch)
tb_plot <- tb_plot %>%
  dplyr::mutate(study = factor(study, levels = studies)) %>%
  dplyr::mutate(p_levels =
                  dplyr::case_when(
                    pval <= 0.001 ~ "***",
                    pval <= 0.01 ~ "**",
                    pval <= 0.05 ~ "*",
                    TRUE ~ ""
                  ))
readr::write_tsv(tb_plot, paste0(dir_outputChunk, "PERMANOVA.tsv"))
levels_variable <- c("stool/biopsy", "biopsy_site", "race", "race_missing",
                     "gender", "gender_missing", "age.cat", "age.cat_missing",
                     "age_at_diagnosis.cat", "age_at_diagnosis.cat_missing",
                     "disease", "L.cat", "L.cat_missing", "B.cat", "B.cat_missing",
                     "E.cat", "E.cat_missing",
                     "antibiotics", "antibiotics_missing", 
                     "immunosuppressants", "immunosuppressants_missing",
                     "steroids", "steroids_missing",
                     "mesalamine_5ASA", "mesalamine_5ASA_missing",
                     "batch", "subject")
p <- tb_plot %>%
  dplyr::mutate(variable = 
                  ifelse(is_NA == "non_missing",
                         variable,
                         paste0(variable, "_missing"))) %>% 
  dplyr::mutate(variable = factor(variable, 
                                  levels = rev(levels_variable))) %>% 
  ggplot(aes(x = study, y = variable, fill = R2)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "black", trans = "log10", na.value = "white") +
  geom_text(aes(label = ifelse(is.na(R2),
                               NA,
                               paste0(round(R2*100, digits = 2), "%\n",
                                      p_levels))),
            color = "red") +
  theme(line = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.border = element_blank()) +
  rotate_xaxis(15)
ggsave(filename = paste0(dir_outputChunk, "PERMANOVA.pdf"), 
       p,
       width = 9, height = 11)
```

# Maaslin2
```{r load data}
source("assets/ma_tests.R")
load("data/phyloseq/species.RData")
metadata <- sample_data2(phylo_species)
```

```{r Maaslin2}
dir_outputChunk <- paste0(dir_output, "Maaslin2/")
dir.create(dir_outputChunk)

metadata_test <- metadata %>% 
  dplyr::mutate(race_fill = fill_na(race),
                gender_fill = fill_na(gender),
                age.cat_fill = 
                  dplyr::case_when(age < 18 ~ "child",
                                   !is.na(age) ~ "adult",
                                   TRUE ~ NA_character_) %>% fill_na,
                age_at_diagnosis.cat_fill = 
                  dplyr::case_when(age_at_diagnosis < 18 ~ "A1",
                                   age_at_diagnosis < 40 ~ "A2",
                                   !is.na(age_at_diagnosis) ~ "A3",
                                   TRUE ~ NA_character_) %>% fill_na,
                study_site = paste(dataset_name, 
                                   sample_type, 
                                   sep = "_"),
                study_site_disease = paste(dataset_name, 
                                           sample_type, 
                                           disease, sep = "_"),
                subject_accession_longitudinal =
                  ifelse(dataset_name %in%
                           studies_longitudinal,
                         subject_accession,
                         NA_character_))

for(feature_level in c("species")) {
  dir.create(paste0(dir_outputChunk, feature_level, "/"))
  load(paste0("data/phyloseq/", feature_level, ".RData"))
  mat_otu <- get(paste0("phylo_", feature_level)) %>% 
    transform_sample_counts(tss) %>%  
    otu_table2
  
  l_results <- list()
  for(test in names(l_tests)) {
    print(test)
    test_param <- l_tests[[test]]
    result <- fit_metaAnalysis(mat_otu = mat_otu,
                               data = metadata_test %>%
                                 dplyr::filter(!!test_param$exprs_filter),
                               test_variable = test_param$test_variable,
                               contrasts = test_param$contrasts,
                               batch_variable = test_param$batch_variable,
                               covariates = test_param$covariates,
                               covariates.random =
                                 test_param$covariates.random,
                               moderator_variables =
                                 test_param$moderator_variables,
                               n_features = 50,
                               normalization = "TSS",
                               transform = "AST",
                               analysis_method = "LM",
                               rma_method = "REML",
                               directory = paste0(dir_outputChunk,
                                                  feature_level, "/",
                                                  test, "/"),
                               forest.plots = TRUE,
                               verbose = FALSE)
    save(result, file = paste0(dir_outputChunk, feature_level, "/",
                               test, "/result.RData"))
    # load(paste0(dir_outputChunk, feature_level, "/",
    #             test, "/result.RData"))
    l_results[[test]] <- result
  }
  result_all <- l_results %>%
    purrr::imap_dfr(function(result, test) {
      result$tb_summarise %>%
        tidyr::gather(key = study, value = weight, dplyr::matches("weight_")) %>%
        dplyr::group_by_at(vars(-weight, -study)) %>%
        dplyr::arrange(desc(weight)) %>%
        dplyr::summarise(max_weight = weight[1],
                         study_max_weight = study[1]) %>%
        dplyr::ungroup() %>%
        dplyr::mutate(study_max_weight = study_max_weight %>%
                        stringr::str_replace_all("weight\\_", ""),
                      test = test,
                      q.fdr_meta = ifelse(k > 2,
                                          pval,
                                          NA_real_) %>%
                        p.adjust(method = "fdr"))
    })
  readr::write_tsv(result_all, paste0(dir_outputChunk,
                                      feature_level,
                                      "/all_results.tsv"))
  
  # Visualization
  # disease status
  plot_metaAnalysis(l_results, tests_disease, "disease",
                    paste0(dir_outputChunk, feature_level, "/"))
  # disease subtype
  plot_metaAnalysis(l_results, tests_diseaseSubtype, "disease_subtype",
                    paste0(dir_outputChunk, feature_level, "/"))
  # treatment
  plot_metaAnalysis(l_results, tests_treatment, "treatment",
                    paste0(dir_outputChunk, feature_level, "/"))
  # covariate
  plot_metaAnalysis(l_results, tests_covariate, "covariate",
                    paste0(dir_outputChunk, feature_level, "/"))
}
```
# Compare Maaslin results before and after adjustment
```{r Maaslin2 OTU vs. species}
dir_outputChunk <- paste0(dir_output, "comparison/")
dir.create(dir_outputChunk)
for(test in names(l_tests)) {
  tb_after <- readr::read_tsv(paste0("results/4-association/Maaslin2/species/", 
                                     test, 
                                     "/results.tsv")) %>% 
    dplyr::filter(k >= 2) %>% 
    dplyr::mutate(q_fdr = p.adjust(pval, "fdr")) %>% 
    dplyr::filter(q_fdr < 0.05)
  tb_before <- readr::read_tsv(paste0("results/4-association/sensitivity/Maaslin2/species/", 
                                      test, 
                                      "/results.tsv")) %>% 
    dplyr::filter(k >= 2) %>% 
    dplyr::mutate(q_fdr = p.adjust(pval, "fdr"))
  tb_comparison <- tb_after %>% 
    dplyr::left_join(tb_before, by = "feature", suffix = c("", "_before")) %>% 
    dplyr::arrange(beta) %>% 
    dplyr::mutate(feature = factor(feature) %>% forcats::fct_inorder())
  p_beta <- tb_comparison %>% 
    dplyr::select(feature, beta, beta_before) %>% 
    tidyr::gather(key = "adjustment", value = "beta", beta, beta_before) %>% 
    ggplot(aes(x = feature, y = beta, fill = adjustment)) +
    geom_bar(stat = "identity", position = position_dodge()) +
    coord_flip() +
    guides(fill = FALSE)
  p_pval <- tb_comparison %>% 
    dplyr::select(feature, q_fdr, q_fdr_before) %>% 
    tidyr::gather(key = "adjustment", value = "q_fdr", q_fdr,q_fdr_before) %>% 
    ggplot(aes(x = feature, y = -log10(q_fdr), fill = adjustment)) +
    geom_hline(yintercept = -log10(0.05)) +
    geom_bar(stat = "identity", position = position_dodge()) +
    coord_flip() +
    guides(fill = FALSE) +
    no_label_yaxis()
  p_I2 <- tb_comparison %>% 
    dplyr::select(feature, I2, I2_before) %>% 
    tidyr::gather(key = "adjustment", value = "I2", I2, I2_before) %>% 
    ggplot(aes(x = feature, y = I2, fill = adjustment)) +
    geom_bar(stat = "identity", position = position_dodge()) +
    coord_flip() +
    no_label_yaxis()
  p <- cowplot::plot_grid(p_beta, p_pval, p_I2, rel_widths = c(5, 2, 2), nrow = 1)
  ggsave(file = paste0(dir_outputChunk, test, ".pdf"),
         p, width = 18, height = max(nrow(tb_after)/5, 5))
}
# scatter plots
pdf(paste0(dir_outputChunk, "comparison_scatters.pdf"),
    width = 20,
    height = 5)
for(test in names(l_tests)) {
  tb_after <- readr::read_tsv(paste0("results/4-association/Maaslin2/species/", 
                                     test, 
                                     "/results.tsv")) %>% 
    dplyr::filter(k >= 2) %>% 
    dplyr::mutate(q_fdr = p.adjust(pval, "fdr")) %>% 
    dplyr::filter(q_fdr < 0.05)
  if(nrow(tb_after) == 0) next
  tb_before <- readr::read_tsv(paste0("results/4-association/sensitivity/Maaslin2/species/", 
                                      test, 
                                      "/results.tsv")) %>% 
    dplyr::filter(k >= 2) %>% 
    dplyr::mutate(q_fdr = p.adjust(pval, "fdr"))
  tb_comparison <- tb_after %>% 
    dplyr::left_join(tb_before, by = "feature", suffix = c("", "_before"))
  p_beta <- tb_comparison %>% 
    ggplot(aes(x = beta, y = beta_before)) +
    geom_abline(slope = 1, intercept = 0, color = "red") +
    geom_hline(yintercept = 0, linetype = "dashed") + 
    geom_vline(xintercept = 0, linetype = "dashed") +
    geom_point()
  p_sd <- tb_comparison %>% 
    ggplot(aes(x = se, y = se_before)) +
    geom_abline(slope = 1, intercept = 0, color = "red") +
    geom_point()
  p_pval <- tb_comparison %>% 
    ggplot(aes(x = -log10(pval), y = -log10(pval_before))) +
    geom_abline(slope = 1, intercept = 0, color = "red") +
    geom_hline(yintercept = -log10(0.05), linetype = "dashed") + 
    geom_vline(xintercept = -log10(0.05), linetype = "dashed") +
    geom_point()
  p_I2 <- tb_comparison %>% 
    ggplot(aes(x = I2, y = I2_before)) +
    geom_abline(slope = 1, intercept = 0, color = "red") +
    geom_point()
  p_I2_moderator <- tb_comparison %>% 
    ggplot(aes(x = I2_moderator, y = I2_moderator_before)) +
    geom_abline(slope = 1, intercept = 0, color = "red") +
    geom_point()
  p <- cowplot::plot_grid(p_beta, p_sd, p_pval, p_I2,
                          labels = c("beta", "std.err", "-log10 pval", "I2"),
                          nrow = 1) %>% 
    cowplot_title(title = test)
  print(p)
}
dev.off()
```
