---
title: "4.1-check E coli"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  df_print: paged
---
# Overview
E coli is not present in OTU table due to classification of greengenes. But are they in the top differential abundance results between IBD and control?
```{r setup, echo = FALSE}                                           
knitr::opts_knit$set(root.dir = "..")
```
```{r setup2, message=FALSE, warning=FALSE, echo = FALSE}
for(i.function in list.files("functions/", full.names = TRUE)) {
  source(i.function)
}
setup(getwd())
dir_output <- "results/4-association/"
dir.create(dir_output, recursive = TRUE, showWarnings = FALSE)
```
# PERMANOVA
```{r PERMANOVA}
l_phylo <- list()
for(study in studies) {
  load(paste0("data/phyloseq/", study, "/otus.RData"))
  l_phylo[[study]] <- phylo
}
tb_otus <- l_phylo %>% 
  purrr::imap_dfr(function(phylo, study) {
    phylo %>% 
      tax_table2() %>% as.data.frame(stringsAsFactors = FALSE) %>% 
      tibble::rownames_to_column("otu") %>% 
      dplyr::mutate(genera = paste(Rank1, Rank2, Rank3, Rank4, Rank5, Rank6,
                                   sep = "|"),
                    study = study)
  })
genus_check <- "k__Bacteria|p__Proteobacteria|c__Gammaproteobacteria|o__Enterobacteriales|f__Enterobacteriaceae|g__"
tb_otus %>% 
  dplyr::filter(!duplicated(otu)) %>% 
  dplyr::filter(genera %in% genus_check) %>% 
  View
```