---
title: "4.1-association_permanova"
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
html_document:
df_print: paged
---
# Overview
Perform PERMANOVA analysis on covariates.

```{r setup, echo = FALSE}                                           
knitr::opts_knit$set(root.dir = normalizePath(".."))
```
```{r setup2, message=FALSE, warning=FALSE, echo = FALSE}
rm(list = ls())
for(i.function in list.files("functions/", full.names = TRUE)) {
  source(i.function)
}
setup(getwd())
dir_output <- "results/4.1-permanova/"
dir.create(dir_output, recursive = TRUE, showWarnings = FALSE)
```

# PERMANOVA
```{r PERMANOVA}
print(studies)
dir_outputChunk <- paste0(dir_output, "PERMANOVA/")
dir.create(dir_outputChunk)
load("data/phyloseq/genera_adj.RData")
load("data/distance/dist_genera_adj.RData")
load("data/distance/dist_genera.RData")
n_permutations <- 3 # set # permuations for PERMANOVA
ncores <- 3

metadata <- sample_data2(phylo_genera_adj)
metadata_test <- metadata %>% 
  dplyr::mutate(age.cat = 
                  dplyr::case_when(age < 18 ~ "child",
                                   !is.na(age) ~ "adult",
                                   TRUE ~ NA_character_),
                age_at_diagnosis.cat = 
                  dplyr::case_when(age_at_diagnosis < 18 ~ "A1",
                                   age_at_diagnosis < 40 ~ "A2",
                                   !is.na(age_at_diagnosis) ~ "A3",
                                   TRUE ~ NA_character_))

# for(variable in c("race",
#                   "gender",
#                   "age.cat",
#                   "age_at_diagnosis.cat")) {
#   test <- fit_permanova_variable(D = dist_genera_adj,
#                                  variable = variable,
#                                  variable_class = "subject",
#                                  covariates = NULL,
#                                  block_covariates = NULL,
#                                  block_variable = "subject_accession",
#                                  data = metadata_test,
#                                  permutations = n_permutations,
#                                  ncores = ncores)
#   assign(paste0("fit_adonis_", variable),
#          test)
#   save(list = paste0("fit_adonis_", variable),
#        file = paste0(dir_output, "fit_adonis_", variable, ".RData"))
#   rm(list = c("test", paste0("fit_adonis_", variable)))
# }
# 
# for(variable in c("B.cat", "L.cat", "E.cat",
#                   "antibiotics",
#                   "immunosuppressants",
#                   "steroids",
#                   "mesalamine_5ASA")) {
#   test <- fit_permanova_variable(D = dist_genera_adj,
#                                  variable = variable,
#                                  variable_class = "sample",
#                                  covariates = NULL,
#                                  block_covariates = "disease",
#                                  block_variable = "subject_accession",
#                                  data = metadata_test,
#                                  permutations = n_permutations,
#                                  ncores = ncores)
#   assign(paste0("fit_adonis_", variable),
#          test)
#   save(list = paste0("fit_adonis_", variable),
#        file = paste0(dir_output, "fit_adonis_", variable, ".RData"))
#   rm(list = c("test", paste0("fit_adonis_", variable)))
# }
# 
# fit_adonis_disease <-
#   fit_permanova_variable(D = dist_genera_adj,
#                          variable = "disease",
#                          variable_class = "subject",
#                          covariates = NULL,
#                          block_covariates = NULL,
#                          block_variable = "subject_accession",
#                          data = metadata_test,
#                          permutations = n_permutations,
#                          ncores = ncores)
# save(fit_adonis_disease, file = paste0(dir_output, "fit_adonis_disease.RData"))
# rm(fit_adonis_disease)
# 
# fit_adonis_bodySite <-
#   fit_permanova_variable(D = dist_genera_adj,
#                          variable = "body_site",
#                          variable_class = "sample",
#                          covariates = "sample_type",
#                          block_covariates = NULL,
#                          block_variable = "subject_accession",
#                          data = metadata_test,
#                          permutations = n_permutations,
#                          ncores = ncores)
# save(fit_adonis_bodySite, file = paste0(dir_output, "fit_adonis_bodySite.RData"))
# rm(fit_adonis_bodySite)
# 
# fit_adonis_study_before <-
#   fit_permanova_variable(D = dist_genera, 
#                          variable = "dataset_name",
#                          variable_class = "subject",
#                          covariates = NULL,
#                          block_covariates = NULL,
#                          block_variable = "subject_accession",
#                          data = metadata_test,
#                          permutations = n_permutations, 
#                          ncores = ncores)
# save(fit_adonis_study_before, file = paste0(dir_output, "fit_adonis_study_before.RData"))
# rm(fit_adonis_study_before)
# 
# fit_adonis_subject <-
#   fit_permanova_variable(D = dist_genera_adj, 
#                          variable = "subject_accession",
#                          variable_class = "subject",
#                          covariates = NULL,
#                          block_covariates = "dataset_name",
#                          block_variable = "subject_accession",
#                          data = metadata_test,
#                          permutations = n_permutations, 
#                          ncores = ncores)
# save(fit_adonis_subject, file = paste0(dir_output, "fit_adonis_subject.RData"))
# rm(fit_adonis_subject)
```

```{r PERMANOVA per study}
for(study in studies) {
  print(study)
  dir.create(paste0(dir_output, study, "/"), recursive = TRUE, showWarnings = TRUE)
  metadata_test_tmp <- subset(metadata_test, dataset_name == study)
  dist_genera_adj_tmp <- subset_distance(dist_genera_adj,
                                         metadata_test$dataset_name == study)
  dist_genera_tmp <- subset_distance(dist_genera,
                                     metadata_test$dataset_name == study)
  
  for(variable in c("race",
                    "gender",
                    "age.cat",
                    "age_at_diagnosis.cat")) {
    if(all(is.na(metadata_test_tmp[, variable])) |
       metadata_test_tmp[, variable] %>% setdiff(NA) %>% 
       length %>% unique %>% is_less_than(2)) {
      test <- NULL
      assign(paste0("fit_adonis_", variable),
             test)
      save(list = paste0("fit_adonis_", variable),
           file = paste0(dir_output, study, "/fit_adonis_", variable, ".RData"))
      rm(list = c("test", paste0("fit_adonis_", variable)))
      next
    } 
    test <- fit_permanova_variable(D = dist_genera_adj_tmp,
                                   variable = variable,
                                   variable_class = "subject",
                                   covariates = NULL,
                                   block_covariates = NULL,
                                   block_variable = "subject_accession",
                                   data = metadata_test_tmp,
                                   permutations = n_permutations,
                                   ncores = ncores)
    assign(paste0("fit_adonis_", variable),
           test)
    save(list = paste0("fit_adonis_", variable),
         file = paste0(dir_output, study, "/fit_adonis_", variable, ".RData"))
    rm(list = c("test", paste0("fit_adonis_", variable)))
  }
  
  for(variable in c("B.cat", "L.cat", "E.cat",
                    "antibiotics",
                    "immunosuppressants",
                    "steroids",
                    "mesalamine_5ASA")) {
    if(all(is.na(metadata_test_tmp[, variable])) |
       metadata_test_tmp[, variable] %>% setdiff(NA) %>% 
       length %>% unique %>% is_less_than(2)) {
      test <- NULL
      assign(paste0("fit_adonis_", variable),
             test)
      save(list = paste0("fit_adonis_", variable),
           file = paste0(dir_output, study, "/fit_adonis_", variable, ".RData"))
      rm(list = c("test", paste0("fit_adonis_", variable)))
      next
    }
    test <- fit_permanova_variable(D = dist_genera_adj_tmp,
                                   variable = variable,
                                   variable_class = "sample",
                                   covariates = NULL,
                                   block_covariates = "disease",
                                   block_variable = "subject_accession",
                                   data = metadata_test_tmp,
                                   permutations = n_permutations,
                                   ncores = ncores)
    assign(paste0("fit_adonis_", variable),
           test)
    save(list = paste0("fit_adonis_", variable),
         file = paste0(dir_output, study, "/fit_adonis_", variable, ".RData"))
    rm(list = c("test", paste0("fit_adonis_", variable)))
  }
  
  if(length(unique(metadata_test_tmp$disease)) < 2) {
    fit_adonis_disease <- NULL
  } else {
    fit_adonis_disease <-
      fit_permanova_variable(D = dist_genera_adj_tmp,
                             variable = "disease",
                             variable_class = "subject",
                             covariates = NULL,
                             block_covariates = NULL,
                             block_variable = "subject_accession",
                             data = metadata_test_tmp,
                             permutations = n_permutations,
                             ncores = ncores)
  }
  save(fit_adonis_disease, file = paste0(dir_output, study, "/fit_adonis_disease.RData"))
  rm(fit_adonis_disease)
  
  if(length(unique(metadata_test_tmp$body_site)) < 2) {
    fit_adonis_bodySite <- NULL
  } else {
    if(all(metadata_test_tmp$sample_type == "biopsy")) {
      fit_adonis_bodySite <-
        fit_permanova_variable(D = dist_genera_adj_tmp,
                               variable = "body_site",
                               variable_class = "sample",
                               covariates = NULL,
                               block_covariates = NULL,
                               block_variable = "subject_accession",
                               data = metadata_test_tmp,
                               permutations = n_permutations,
                               ncores = ncores)
    } else {
      fit_adonis_bodySite <-
        fit_permanova_variable(D = dist_genera_adj_tmp,
                               variable = "body_site",
                               variable_class = "sample",
                               covariates = "sample_type",
                               block_covariates = NULL,
                               block_variable = "subject_accession",
                               data = metadata_test_tmp,
                               permutations = n_permutations,
                               ncores = ncores)
    }
  }
  save(fit_adonis_bodySite, file = paste0(dir_output, study, "/fit_adonis_bodySite.RData"))
  rm(fit_adonis_bodySite)
  
  if(all(is.na(metadata_test_tmp$batch))) {
    fit_adonis_batch <- NULL
    fit_adonis_batch_before <- NULL 
  } else {
    fit_adonis_batch <- fit_permanova_variable(D = dist_genera_adj_tmp,
                               variable = "batch",
                               variable_class = "sample",
                               covariates = NULL,
                               block_covariates = NULL,
                               block_variable = "subject_accession",
                               data = metadata_test_tmp,
                               permutations = n_permutations,
                               ncores = ncores)
     fit_adonis_batch_before <- fit_permanova_variable(D = dist_genera_tmp,
                               variable = "batch",
                               variable_class = "sample",
                               covariates = NULL,
                               block_covariates = NULL,
                               block_variable = "subject_accession",
                               data = metadata_test_tmp,
                               permutations = n_permutations,
                               ncores = ncores)
  }
 save(fit_adonis_batch, file = paste0(dir_output, study, "/fit_adonis_batch.RData"))
 save(fit_adonis_batch_before, file = paste0(dir_output, study,
                                             "/fit_adonis_batch_before.RData"))
 rm(fit_adonis_batch)
 rm(fit_adonis_batch_before)
    
 fit_adonis_subject <-
  fit_permanova_variable(D = dist_genera_adj_tmp, 
                         variable = "subject_accession",
                         variable_class = "subject",
                         covariates = NULL,
                         block_covariates = NULL,
                         block_variable = "subject_accession",
                         data = metadata_test_tmp,
                         permutations = n_permutations, 
                         ncores = ncores)
  save(fit_adonis_subject, 
       file = paste0(dir_output, study, "/fit_adonis_subject.RData"))
}
```
