---
title: "4.3-montreal  "
author: "Siyuan Ma"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
html_document:
df_print: paged
---
# Overview
Test for directional change on CD Behavior and UC Extent

```{r setup, echo = FALSE}                                           
knitr::opts_knit$set(root.dir = normalizePath(".."))
```

```{r setup2, include=FALSE}
smar::sourceDir("functions/", recursive = FALSE)
setup("./")
dir_output <- "results/4.3-montreal/"
dir.create(dir_output, recursive = TRUE, showWarnings = TRUE)
```

# Testing for directional change on CD Behavior and UC Extent
```{r trend test}
source("assets/ma_tests.R")
load("data/physeq/genera_adj.RData")
metadata <- smar::sample_data2(physeq_genera_adj)

metadata_test <- metadata %>% 
  dplyr::mutate(race_fill = fill_na(race),
                gender_fill = fill_na(gender),
                age.cat_fill = 
                  dplyr::case_when(age < 18 ~ "child",
                                   !is.na(age) ~ "adult",
                                   TRUE ~ NA_character_) %>% fill_na,
                study_site = paste(dataset_name, 
                                   sample_type, 
                                   sep = "_"),
                subject_accession_longitudinal =
                  ifelse(dataset_name %in%
                           studies_longitudinal,
                         subject_accession,
                         NA_character_)) %>% 
  dplyr::group_by(study_site) %>% 
  dplyr::mutate(B.avail = dplyr::n_distinct(B.cat, na.rm = TRUE) == 3,
                E.avail = dplyr::n_distinct(E.cat, na.rm = TRUE) == 3) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(B23 = ifelse(B.cat %in% c("B2", "B3"),
                             1,
                             0),
                B3 = ifelse(B.cat == "B3",
                            1,
                            0),
                E23 = ifelse(E.cat %in% c("E2", "E3"),
                             1,
                             0),
                E3 = ifelse(E.cat == "E3",
                            1,
                            0))


for(feature_level in "genera") {
  dir.create(paste0(dir_output, feature_level, "/"))
  load(paste0("data/physeq/", feature_level, "_adj.RData"))
  mat_otu_adj <- get(paste0("physeq_", feature_level, "_adj")) %>% 
    to_relativeAbundance() %>%  
    smar::otu_table2()
  
  l_results <- list()
  for(test in names(l_tests_subtype)) {
    print(test)
    test_param <- l_tests_subtype[[test]]
    result <- fit_metaAnalysis(feature.abd = mat_otu_adj,
                               data = metadata_test %>%
                                 dplyr::filter(!!test_param$exprs_filter),
                               test_variable = test_param$test_variable,
                               contrasts = test_param$contrasts,
                               batch_variable = test_param$batch_variable,
                               covariates = test_param$covariates,
                               covariates.random =
                                 test_param$covariates.random,
                               moderator_variables =
                                 test_param$moderator_variables,
                               n_features = 50,
                               normalization = "NONE",
                               transform = "AST",
                               analysis_method = "LM",
                               rma.method = "REML",
                               output = paste0(dir_output,
                                                  feature_level, "/",
                                                  test, "/"),
                               forest.plots = TRUE,
                               verbose = FALSE,
                               rma.threshold = 1e-6,
                               rma.maxiter = 2000)
    save(result, file = paste0(dir_output, feature_level, "/",
                               test, "/result.RData"))
    l_results[[test]] <- result
  }
  for(test in c("B2_vs_B1", "B3_vs_B1",
                "E2_vs_E1", "E3_vs_E1")) {
    print(test)
    load(paste0("results/4.2-maaslin2/", feature_level, "/",
                test, "/result.RData"))
    l_results[[test]] <- result
  }
  
  plot_metaAnalysis(l_results, c("B2_vs_B1", "B3_vs_B1", "CD Behavior", 
                                 "E2_vs_E1", "E3_vs_E1", "UC Extent"), 
                    "disease_subtype_direction",
                    paste0(dir_output, feature_level, "/"))
}
```
